import Navbar from "../components/Navbar";
import {Roboto} from 'next/font/google'
import './global.css'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const font = Roboto({
  weight:['300','400','500','700'],
  style: ['italic', 'normal'],
  subsets: ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body >
        <Navbar />
        <main className='container mx-auto h-screen flex justify-center items-center'>
        {children}
        </main>
        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
      </body>
    </html>
  );
}
